'use server';
/**
 * @fileOverview Provides a GenAI-powered summary of predictive forecasting results.
 *
 * - predictiveForecastingSummary - A function that generates a summary of predictive forecasting results.
 * - PredictiveForecastingSummaryInput - The input type for the predictiveForecastingSummary function.
 * - PredictiveForecastingSummaryOutput - The return type for the predictiveForecastingSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PredictiveForecastingSummaryInputSchema = z.object({
  historicalData: z.string().describe('Historical data used for forecasting.'),
  forecastedData: z.string().describe('Forecasted data generated by the predictive model.'),
  relevantBusinessContext: z.string().describe('The description of the business and its context.'),
});
export type PredictiveForecastingSummaryInput = z.infer<typeof PredictiveForecastingSummaryInputSchema>;

const PredictiveForecastingSummaryOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the predictive forecasting results.'),
  keyTrends: z.string().describe('Identified key trends from the forecasted data.'),
  potentialRisks: z.string().describe('Potential risks and opportunities based on the forecast.'),
});
export type PredictiveForecastingSummaryOutput = z.infer<typeof PredictiveForecastingSummaryOutputSchema>;

export async function predictiveForecastingSummary(
  input: PredictiveForecastingSummaryInput
): Promise<PredictiveForecastingSummaryOutput> {
  return predictiveForecastingSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'predictiveForecastingSummaryPrompt',
  input: {schema: PredictiveForecastingSummaryInputSchema},
  output: {schema: PredictiveForecastingSummaryOutputSchema},
  prompt: `You are an expert in data analytics and business forecasting.

  Based on the historical data, forecasted data, and relevant business context, generate a concise summary highlighting key takeaways, trends, potential risks, and opportunities.

  Historical Data: {{{historicalData}}}
  Forecasted Data: {{{forecastedData}}}
  Business Context: {{{relevantBusinessContext}}}

  Summary:
  `, // Ensure that output contains a good summary
});

const predictiveForecastingSummaryFlow = ai.defineFlow(
  {
    name: 'predictiveForecastingSummaryFlow',
    inputSchema: PredictiveForecastingSummaryInputSchema,
    outputSchema: PredictiveForecastingSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
